docu/examples/example4-wavechecking.ipf
procedures/unit-testing-comparators.ipf

I fixed your comprehensive unit-testing-framework a little bit.
In old version, checking for text waves is not work.
```
CHECK_WAVE({0,1,2}, TEXT_WAVE) // This test passes. 
``` 
I fixed TEST_WAVE_WRAPPER function and example4-wavechecking.ipf.

Fix TEST_WAVE_WRAPPER

---

procedures/unit-testing-comparators.ipf

I add wrapper functions to test text waves.
One can write text wave literal in test code.
```igorpro
CHECK_EQUAL_WAVES( somefunction(), {1,2,3} ) // ok
CHECK_EQUAL_WAVES( somefunction(), {"a","b","c"} ) // compile error!
CHECK_EQUAL_TEXTS( somefunction(), {"a","b","c"} ) // ok!
```
Please check it!

Add wrapper functions for text waves

---

procedures/unit-testing-basics.ipf

Using printf in that way is unsafe as message could hold unescaped "%"
thus leadint to a RTE.
Or to an Igor crash (fixed with the IP8 nightly from today).
Let's use it correctly.
Bug introduced in a7ab54cb (More detailed RTE error message,
2017-03-07).
Closes #15.
Igor should not crash anymore with the test in #15. I could not find another place where we did it wrong.

EvaluateRTE: Avoid Igor crash due to wrong printf usage

---

procedures/unit-testing-basics.ipf

Fix white space errors in comment block section of `RunTest()`,
introduced in fb8ef0ca.

Fix ws errors

---

procedures/unit-testing-basics.ipf

We can't have paragraphs in @param.
Broken since 21b80bd2 (RunTest: Disallow enabling both TAP and JUNIT
output, 2019-03-13).

RunTest: Fix documentation

---

procedures/unit-testing-autorun.ipf
procedures/unit-testing-basics.ipf

Since forever we bugged out if the run function aborts or multiple run
functions exist.
Handle both cases gracefully and quit Igor Pro on error as well.

AfterFileOpenHook: Make it more robust

---

.gitlab-ci.yml

The documentation is built directly from a docker container instead of
building the container via make / docker procedure.
Better fix for
https://github.com/byte-physics/igor-unit-testing-framework/pull/70

Use Docker Image For Documentation

---

procedures/unit-testing-basics.ipf
procedures/unit-testing-comparators.ipf

This makes it much faster to understand failing tests.

*_EQUAL_WAVES: Report the EqualWaves mode as string

---

procedures/unit-testing-autorun.ipf

Since IP7 functions can be declared as override and thus we can find
multiple functions called "run".
Let Igor handle figuring out which function to call and just ensure that
we find at least one function.
Broken since forever.

Autorun: Handle multiple run functions

---

procedures/unit-testing-basics.ipf

Close #77.
Sample output in our CI docker instances:
```
[...]
[notice] Version: Igor Pro 8.03 64-bit
[debug] Version (short): v8m03
Start of test "Unnamed"
Entering test suite "example6-automatic-invocation.ipf"
Entering test case "Example6#CheckTrigonometricFunctions"
Leaving test case "Example6#CheckTrigonometricFunctions"
Finished with no errors
Leaving test suite "example6-automatic-invocation.ipf"
Test finished with no errors
End of test "Unnamed"
[...]
```

Output status messages to stdout as well

---

procedures/unit-testing-basics.ipf

The following test case
Function MyTest()
Make data
Display data
End
and executing it with default flags results in an error in the
TestCaseEnd hook as the workFolder can not be killed, as the displayed
wave still lives in that.
Just ignore the error as we can not do anything else.

TestCaseEnd: Silently ignore non-killable working folder

---

.gitlab-ci.yml
docu/sphinx/Makefile

- this allows developers to deploy the Igor UTF incl. docu to a separated
internal staging area for review.
- the location is defined through the used lftp bookmark in
/docu/sphinx/Makefile section deploy_staging.

Added manual deployment job to CI to staging area

---

procedures/unit-testing-junit.ipf

In order to fulfill ISO8601 the timezone needed to be removed from the timestamp.
closes #25

Timezone dropped from JU_GetISO8601TimeStamp()

---

docu/sphinx/source/basic.rst
internal_dev/testcase_order.ipf
procedures/unit-testing-basics.ipf
procedures/unit-testing-utils.ipf

Multidata tests and normal tests now come in the right order.
.ipf file for quick tests is attached:
[issue109-sorting-testcases.zip](https://github.com/byte-physics/igor-unit-testing-framework/files/4591389/issue109-sorting-testcases.zip)
I have the feeling that in sortTestCaseList the second for-loop could be solved in a 1-liner, but have no idea how.
Edit: closes #109

Issue109 sorting testcases

---

procedures/unit-testing-basics.ipf

In a first step printFailInfo was updated to use the function UTF_PrintStatusMessage (not necessary, but it should make the output more unified) instead of a simple print.
In the second step the error handling in TestCaseEnd when the assertion counter equals 0 was changed. It does not simply print to the console without anything else, but also uses the standard ReportResults to increase the error counter and send messages via PrintFailInfo.
To get the right error message an additional return-case needed to be inserted in getInfo to get the previous message. Furthermore the case "Assertion failed in unknown location" now only triggers if the assertion counter is unequal 0. This should be no problem, because ReportResults is only called from unit-testing-assertion-wrappers.ipf, which only …

Ma issue92 error if no assertion

---

docu/examples/example3-plain.ipf
docu/sphinx/source/examples.rst
procedures/unit-testing-basics.ipf

A RTE is now detected even if the abort flag is set. incrError was moved inside EvaluateRTE, because it belongs together.
An Error in the explanation of example3 was found, and example3 was expanded to show that an abort stops the whole test run.
Edit: Closes #102

MA issue102 leftover RTE

---

docu/sphinx/source/examples.rst
procedures/unit-testing-assertion-wrappers.ipf
procedures/unit-testing-assertions.ipf

In the first commit an error in Example4 was corrected.
After that the description for CHECK_EQUAL_WAVES was changed to state that the function only checks the content.
I tried to add the reference to CHECK_WAVES as clickable link, but it did not work easily.
Closes: #114

Ma issue114 docu check equal waves

---

procedures/unit-testing-assertion-wrappers.ipf

Additional information that strings are compared byte-wise without
comparison of the encoding or unicode normalization.
Closes #50

Expanded docu comment about string comparison

---

procedures/unit-testing-assertion-wrappers.ipf
procedures/unit-testing-basics.ipf
procedures/unit-testing-utils.ipf

The debugMode option was added which has 3 bits to set:
0x01: debug on RT error
0x02: debug on NVAR SVAR WAVE reference error
0x04: debug on failed assertion
Closes #10 
Open Questions:
- At the beginning of RunTest(), debugMode is tested to be within 0 and 7. Does it need to be tested for integer values, e.g. by trunk(debugMode) == debugMode ?
- The constants DEBUG_ENABLE and DEBUG_ALLOW have the same value, but are used in different contexts. Is it OK to have two constants?
- EnableIgorDebugger() gives a 4 bit variable to SetIgorDebugger(), which only uses the 3 least significant bits. Is this a possible bug in the future, so it should only pass 3 bits?

MA issue10 debugMode option

---

procedures/unit-testing-basics.ipf

Additionally to the code in the issue, a small comment was added.
Closes #132

Fixed bug for double error after abortNow

---

procedures/unit-testing-basics.ipf
procedures/unit-testing-tap.ipf

If a test case was skipped, it would not appear in TAP output.
Now it gets numbered and marked as OK.

Bugfix TAP now also outputs skipped testcases

---

procedures/unit-testing-basics.ipf

In commit a3ab7ca8 a function was used which was not already implemented
in master, thus breaking UTF. This function was substituted by the function
already in master.
Tests in CI pipeline succeeded.

Bugfix: Mistake from commit a3ab7ca8 fixed

---

procedures/unit-testing-basics.ipf

Now the return only contains the module if the function is declared static.
Furthermore the code was cleaned up to apply better to our coding conventions.
Edit:
Tested with example5 (local and global hooks), output was exactly the same.
Tested with multiple data generators. Now UTF only finds data generators inside the same procedure file (as was intended), generator names like module#generator are not working (will be changed with issue#111).
Closes #142

GetFullFunctionName bugfix to append module only when needed

---

docu/sphinx/source/_static/js/matomo.js

This loads faster than the uncompressed one. See
https://github.com/matomo-org/matomo/tree/4.x-dev/js for the
documentation.

Matomo: Use the compressed javascript version

---

.gitlab-ci.yml

Introduced with gitlab 13.3 this greatly reduces code duplication. See
also https://docs.gitlab.com/ee/ci/yaml/#parallel-matrix-jobs.

.gitlab-ci.yml: Use new matrix keyword to remove duplicated code

---

docu/sphinx/source/advanced.rst
procedures/unit-testing-basics.ipf

Ever since the introduction of multi data test cases we only warned when
the data generator function could not be used.
This hides buggy test setups and is there bad.
So let's abort in these cases.
The case of an empty generator wave will be handled separately.
Close #99 
@MichaelHuth I went for the abort solution you suggested in https://github.com/byte-physics/igor-unit-testing-framework/pull/131#pullrequestreview-415353210.

CheckFunctionSignaturesTC: Abort on invalid data generator functions

---

.gitlab-ci.yml

As the repositories hosting the docker images are now private, fetching
them fails by default.
By adding project access tokens to these repositories and doing a docker
login, we can now fetch them again.

.gitlab-ci.yml: Provide credentials for docker registries

---

docu/sphinx/source/conf.py

.../conf.py:205:
RemovedInSphinx40Warning: The app.add_javascript() is deprecated. Please
use app.add_js_file() instead.
app.add_javascript('js/matomo.js')

docu/sphinx/source/conf.py: Use non-deprecated method call

---

.gitlab-ci.yml

We only need the submodules for building the documentation.
This speeds up CI.

.gitlab-ci.yml: Only fetch the submodules when needed

---

procedures/unit-testing-basics.ipf

In commit 98f58595e5dfd130d7b1d8e44f728724e70bca6e it was introduced that the
data generator function was enforced to be static when it was present in the
same procedure file.
However when the function is static then the procedure must have a Module
specification. Thus, the logic was changed that it gives an error only if
a static function was found without Module specification.
Also without Module specification (for non-static functions) only the function
name is returned.
Also note that FunctionInfo does not find static functions in other procedure files when called with the function name specification only. So the check is not necessary for the else part.
close https://github.com/byte-physics/igor-unit-testing-framework/issues/175

Fix: Do not enforce Datagenerator function to be static in same procedure.

---

docu/sphinx/source/examples.rst

This is the standard for IP code.
Close #171.

docu/sphinx/source: Always use tab-width of four spaces

---

.gitlab-ci.yml

The default branch changed to main sometime ago, but here we still
reference master.

gitlab-ci.yml: Adapt deployment job for new default branch

---

docu/sphinx/source/advanced.rst
internal_dev/DataGenSpecificWaveTypes.ipf
procedures/unit-testing-basics.ipf
procedures/unit-testing-utils.ipf

In addition to the generic WAVE type multi data test cases also accept now
WAVE/T, WAVE/WAVE and WAVE/DF specific types.
The associated data generators must return waveRef waves where each element
must have the fitting type.
Added examples for all three new typed waves to DataGenSpecificWaveTypes.ipf
in internal_dev.
The MD test case data type setup is not internally buffered for each test case
found. This means that for the actual call to the test case the function
template is determined from the wave type of the element of the data generator
wave.
So for a data generator that returns a wave reference wave with text waves as
elements a test case with WAVE and with WAVE/T is valid. This applies to
reentry functions as well. See also the last example in
DataGenSpecificWaveTypes.ipf.
There …

Introduced typed waves for multi data test cases

---

docu/sphinx/source/advanced.rst
internal_dev/TestCaseAssertionCounterCheck.ipf
procedures/unit-testing-basics.ipf

Only assertions in the test case are counted when enforcing at least one assertion per test case.
A test case spans all code after test case begin to test case end including possible reentry functions.
close https://github.com/byte-physics/igor-unit-testing-framework/issues/113

Enforce assertion in test case, not counting assertions from test hooks

---

procedures/unit-testing-assertion-checks.ipf
procedures/unit-testing-assertion-wrappers.ipf
tests/VTTE.ipf

A fix for invalid parameters for a EqualWaves call in the IUTF was introduced
in 28f7fc37221c117ae3d4a6e5baddd4dd549cc4bb
This created the problem that an RTE that happens in a test case is cleared
at this point in the IUTF and then the RTE gets not visible in the RTE
evaluation. Thus it gets ignored and does not raise an error.
The fix:
EqualWaves is still "monitored" with a AbortOnRTE but not within a try catch
block. If there is a lingering RTE or EqualWaves generates an RTE then the
catch block for the test case takes action and evaluates the RTE.
Thus, wrong parameter passed from CHECK_EQUAL_WAVES to IUTF EqualWaves raise
an RTE that looks like it originates from the test case itself. This is valid
because the CHECK_EQUAL_WAVES parameters are compatible with EqualWaves.
Also mode is …

Fix for RTE cleanup in AreWavesEqual blocking TC RTE evaluation

---

internal_dev/EqualWaves_Examples.ipf
procedures/unit-testing-assertion-checks.ipf
procedures/unit-testing-assertion-wrappers.ipf
procedures/unit-testing-basics.ipf
procedures/unit-testing-utils.ipf
tests/VTTE.ipf

When the data in two waves differ, AreWavesEqual now gives information
where the first and the last difference occured.
FindDifferentWaveEntries, GetWaveIndexInfo and GetWaveDimension funtions
were added in order to work.
Remark: In FindDifferentWaveEntries the built-in function FindLevel was not used, as it returns NAN if already the first element is above the tolerance, or if no element is above the tolerance. That would require an additional step, even though it would be simple if we can assume the second case is impossible because the waves are not equal.
Closes #30

AreWavesEqual creates better message for wave data check

---

procedures/unit-testing-basics.ipf
tests/VTTE.ipf

test calls getTestCaseMatch of the IUTF that calls
getFullFunctionName.
The tests checks if static functions are prepended by the module and
non-static function names have no module name prepended.
close https://github.com/byte-physics/igor-unit-testing-framework/issues/162

Add tests for correct notation of test case names

---

procedures/unit-testing-basics.ipf

Before Function signatures were checked for all found TC unfiltered candidates,
that posed a potential problem if another TC was invalid. Causing an abort,
that prevented execution of the chosen test case.
close https://github.com/byte-physics/igor-unit-testing-framework/issues/105

Function signatures of test cases are now checked after filtering them

---

docu/sphinx/source/flags.rst
procedures/unit-testing-constants.ipf

NULL_WAVE was previously in the general flags section that was correct,
but also confusing. This change removes it from the docu for Minor flags,
which is ok, as testing for null waves through major and minor flags at
the same time is a non practical use case.
close https://github.com/byte-physics/igor-unit-testing-framework/issues/37

Docu: Moved NULL_WAVE flag to Major flags for wave comparison

---

procedures/unit-testing-assertion-wrappers.ipf

The following test case
Function TestMe()
Make/FREE data1
Make/FREE/D data2
CHECK_EQUAL_WAVES(data1, data2, mode = WAVE_DATA | WAVE_DATA_TYPE)
End
does currently produce the following output:
Start of test "Unnamed"
Entering test suite "Procedure"
Entering test case "TestMe"
Assuming equality using mode unknown mode for waves _free_ and _free_: is false. Assertion "CHECK_EQUAL_WAVES(data1, data2, mode = WAVE_DATA | WAVE_DATA_TYPE)" failed in line 11, procedure "Procedure"
Leaving test case "TestMe"
Failed with 1 errors
Leaving test suite "Procedure"
Test finished with 1 errors
End of test "Unnamed"
The reported mode is "unknown" so this is puzzling already. It is also
not clear which mode check failed.
By splitting up each available mode bit into one entry in the modes wave
we gain better …

EQUAL_WAVE_WRAPPER: Make error reporting for custom mode patterns better

---

.gitlab-ci.yml

Incorrectly implemented in 77f099dd (.gitlab-ci.yml: Make warning documentation a CI requirement, 2021-03-19).

.gitlab-ci.yml: Fix the paths for the documentation CI check

---

procedures/unit-testing-junit.ipf

- sprintf has in IP8 a limit of 2400 characters. There were use cases where
the failure message had more characters per line (e.g. wave compare)
- This broke the CI
close https://github.com/byte-physics/igor-unit-testing-framework/issues/211

fix for cutoff output in xml file for messages > 2400 characters

---

docu/sphinx/source/basic.rst

Added a documentation section with example code
close https://github.com/byte-physics/igor-unit-testing-framework/issues/218

Extend documentation with rules for Abort with EXPECTED_FAILURE tag

---

procedures/unit-testing-tracing.ipf

Bug introduced in de9e739c (Multiple changes and fixes, 2021-07-15).

AnalyzeTracingResult: Add missing \r on printf statement

---

docu/sphinx/source/advanced.rst
procedures/unit-testing-basics.ipf

We currently always do instrumentation as soon as the optional
traceWinList parameter is set.
But that is not nice for generic code calling us as that means it has to
branch out.
Accept an empty traceWinList string meaning the same as it being not
present.

RunTest: Allow passing an empty traceWinList

---

docu/sphinx/source/advanced.rst
procedures/unit-testing-tracing.ipf

- The statistics is internally sampled by procedure file, a global result is
output
- Functions marked with the UTF_NOINSTRUMENTATION tag are included in the
code lines number.
close https://github.com/byte-physics/igor-unit-testing-framework/issues/207

Add coverage output to history and stdout at end of traced run

---

procedures/unit-testing-basics.ipf

Due to a wrongly ordered ifdef check for the running IP version the console
output of status messages was for IP9 cut short to the maximum allowed length
of IP8. This was no critical issue but unecessary as IP9 supports full length
strings through fprintf.
The order was fixed and now with IP9 full length status messages are outout to
stdout.

Fix for stdout output of status messages length for IP9

---

procedures/unit-testing-tracing.ipf
tests/test-tracing_instrumented.ipf

The preprocessor endif and else were handled like regular code lines where
counting is done after the line executed. To be in line with the normal
if else endif behavior it was changed.
This applies only to conditionals inside functions.
No conditional replacement of the preprocessor if is possible as calling Z_
requires compiled state.
close https://github.com/byte-physics/igor-unit-testing-framework/issues/235

Added preprocessor endif and else to be counted after the line of appearance

---

docu/sphinx/source/junit.xml

The original junit.xml file from https://llg.cubic.org/docs/junit/ included the
optional testsuite attribute "disabled". This attribute is not included in the
junit.xsd schema file.
For consistency the optional attribute is also removed in the example xml file.
close https://github.com/byte-physics/igor-unit-testing-framework/issues/244

Removed disabled attribute  the junit.xml example file in the documentation

---

procedures/unit-testing-tracing.ipf

Tracing parsed the function declaration types case-sensitive
Thus, for declaration if "variable" declaration is written as "Variable"
then the attribution of lines to the declaration block is aborted early.
since de9e739cd0492ddd2432c01a53a658767494197e

Fix: Tracing must parse function decl types case-insensitive

---

procedures/unit-testing-basics.ipf
procedures/unit-testing-tap.ipf
procedures/unit-testing-tracing.ipf
procedures/unit-testing-utils.ipf
tests/VTTE.ipf

Optimize code by setting up global waves that store most of the data per test case.
Also add global wave to store datagenerator waves and tag values of functions.
Change code to use these new global storages and discard the old obsolete ones.
close https://github.com/byte-physics/igor-unit-testing-framework/issues/168

Revise IUTF setup step

---

procedures/unit-testing-basics.ipf

When running testing with instrumentation and the instrumented code errors out as the code is already instrumented we don't output any history log. This happens with all errors which happen earlier as the history log initialization.
So let's move the initialization to the earliest possible moment.

RunTest: Initialize at the earliest possible moment

---

procedures/unit-testing-basics.ipf
tests/Various.ipf

Every function is now checked to have only optional parameter. This will prevent hooks from used as testcases.
Close #266 .

Fix #266. Test case hooks are evaluated as MD test cases in Igor Pro 6

---

docu/sphinx/source/advanced.rst
docu/sphinx/source/basic.rst

There were a few places in the documentation where it said that a maximum of 4 tags per function are recognised.
This is deprecated since the introduction of MMD test cases. Now all lines up to the previous function can have tags.
This change reflect this new behavior in the documentation.
Close #269.

Documentation: Fix the number of tags

---

procedures/unit-testing-junit.ipf

Ever since the introduction of JUNIT support in 7b71266a (Added JUNIT support, 2017-03-16) we have calculated the durations of a test case or test suite using DateTime.
The default choice for relative time tracking is usually stopmstimer(-2).
And this can also be verified using the following example:
print/D stopmstimer(-2)/1000, stopmstimer(-2)/1000, stopmstimer(-2)/1000, stopmstimer(-2)/1000, stopmstimer(-2)/1000
11962615.9893  11962616.1171  11962616.2341  11962616.3487  11962616.4618
print/D datetime , datetime, datetime, datetime, datetime
3749025804.137  3749025804.137  3749025804.137  3749025804.138  3749025804.138
Here the timestamps for stopmstimer vary with every call, but DateTime stays constant.
So let's use stopMSTimer(-2) for higher accuracy.
This can be verified executing …

unit-testing-junit.ipf: Improve accuracy of test case/suite durations

---

procedures/unit-testing-utils.ipf
tests/Various.ipf

This will trim any trailing zeros after the decimal point of the number and result in nice and short looking numbers. This will also increase the maximum number of digits after the decimal point. Before only 6 digits after the decimal point were shown.
See #221.

Nice number formating for double wave diffs

---

procedures/unit-testing-utils.ipf

In the history normally all four dimensions are shown even if they are not used. With this change only dimensions (up to four) are shown that have a size larger than zero.
This will create an output like:
```
Dimensions|Labels|Value    |
----------|------|---------|
[0]       |      |15.000000|
|      |17.000000|
```
Instead of:
```
Dimensions  |Labels|Value    |
------------|------|---------|
[0][0][0][0]|      |15.000000|
|      |17.000000|
```
See #221.

Show significant dimensions in wave diff

---

procedures/unit-testing-assertion-wrappers.ipf
tests/VTTE.ipf

Enables CHECK_EQUAL_WAVES, WARN_EQUAL_WAVES and REQUIRE_EQUAL_WAVES to accept two identical wave references.
Before this change it will always return an error.
This bug was nowhere mentioned in documentation or test examples.
Close #49

Redesign EQUAL_WAVE_WRAPPER for identical wave references

---

procedures/unit-testing-assertion-wrappers.ipf
procedures/unit-testing-utils.ipf
tests/Various.ipf

Before there was only the reference for the temp waves listed like so:
Wave1: 0x084edf7ad0
Wave2: 0x084edf76b0
This commit add the wave names to this listing:
Wave1: wv1 (0x084edf7ad0)
Wave2: wv_2 (0x084edf76b0)
See #221.

Show wave names in diff temp wave output

---

procedures/unit-testing-assertion-checks.ipf
procedures/unit-testing-assertion-wrappers.ipf
tests/VTTE.ipf

Before checking any wave property the unit testing framework will always
check if the types are compatible. This can yield to unintended behavior
when for example only the sizes should be checked and the waves are
intended to be different typed.
With this change the type check is restructured to enforce same typed
waves only for WAVE_DATA checks.
Close #199.

Enable size only checks for different typed waves

---

procedures/unit-testing-assertion-wrappers.ipf
procedures/unit-testing-utils.ipf
tests/Various.ipf

CHECK_EQUAL_STR, WARN_EQUAL_STR, REQUIRE_EQUAL_STR printed the full content of both strings if there was a mismatch. This is changed using the new string diffing technique introduced in PR #275 for text waves. The new output will only contain the first difference in both strings and some context around.
The new output look like this:
```
String mismatch (case insensitive):
str1: 0:0:0> a
str2: 0:0:0> b
: is false. Assertion "WARN_EQUAL_STR(a, b)" failed in line 13, procedure "Various.ipf"
```
Close #104

Enhance multiline string diff output

---

procedures/unit-testing-assertion-wrappers.ipf

In that way we have always all digits printed out instead of only the first six as %g does.
Close #292.

unit-testing-assertion-wrappers.ipf: Prefer GetNiceStringForNumber

---

procedures/unit-testing-assertion-checks.ipf
procedures/unit-testing-assertion-wrappers.ipf
procedures/unit-testing-constants.ipf
tests/VTTE.ipf
tests/Various.ipf

Makes the output of the wave type more user understandable. This shows the specific type as a string which contains the same names as the flags that are used to specify the type in CHECK_WAVE.
Close #220.

Enhance error reporting in CHECK_WAVE

---

procedures/unit-testing-autorun.ipf
procedures/unit-testing-basics.ipf
procedures/unit-testing-tap.ipf

RunTest got a new optional argument fixLogName for which the output log file get a predictable name. The new file name will be IUTF_Test.log. If this flag is not set the naming will be unchanged and contains the current timestamp.
Close #38.

Enable fixed log file names

---

.gitlab-ci.yml

Set the default timeout for any job to 3 minutes. This time is right now
clamped to 10 minutes because GitLab doesn't support smaller values
right now. [1]
Enable timeout jobs to retry one time. This can happens most times if
Igor is stuck again.
[1]: https://gitlab.com/gitlab-org/gitlab/-/issues/23184
Close: #301.

CI: Specify timeout and retry

---

internal_dev/IM_tap_example1a-uncaught-aborts.ipf
procedures/unit-testing-basics.ipf
procedures/unit-testing-tracing.ipf
procedures/unit-testing-utils.ipf

Abort the test run if some unhandled RTE still exists before CallTestCase(). These errors are most likely a bug in UTF and leave the UTF in an inconsistent state. It is more safe to stop the run at that moment instead of continuing it.
Before this change any RTE that could happen before the run of the test case are just ignored and thrown away.
Close #264.

Abort test run if RTE ocurred in UTF

---

procedures/unit-testing-assertion-checks.ipf
tests/VTTE.ipf

Enables variables in IsVariableSmall to be the same size as the
tolerance to be considered small. Before it has to be smaller than the
tolerance which is unintuitive.
See PR #308.

IsVariableSmall: Change tolerance

---

procedures/unit-testing-basics.ipf

Collect information when and where an assert failed and output the list
at the test run in the history area.
The output format where an assert is located is changed to be more
readable by the user. It also contains the name of the testcase and the
function that contains the assertion now.
Close #193.

Output summary at the end of test run

---

procedures/unit-testing-basics.ipf

Introduce a new convenient method to let a testcase without the use of
assertions fail. This method is only intended to be called outside a
user testcase.
See: PR #297

Reporting: Add TestCaseFail

---

procedures/unit-testing-basics.ipf

During some refactoring of the handling of internal error messages the
error counter got broken. It will increase the error always by one for
each error printing even it was an expected error.
This is now fixed as such as an option was introduced to select if the
error counter should be increased (normally used by UTF errors) or not
(normally the case for UTF assertions).
Close: #311.

FIX: error counter for test assertions

---

procedures/unit-testing-basics.ipf
tests/Various.ipf

During the changes in 09a1dfc (Output summary at the end of test run,
2022-11-11) the output of the assertion message got broken. The message
won't show any longer the assertion line that triggered the error.
A testcase is added to Various to prevent this error in the future.
Fix: #321

Bug-Fix: missing assertion name

---

procedures/unit-testing-basics.ipf

In 9144af0 (Simplify the report of internal errors, 2022-11-03) the
output for internal errors has been simplified. In some cases is
UTF_ToSystemErrorStream called before it's global variable is
initialized which produce a RTE error.
The global variables dfr:messageBuffer, dfr:message, dfr:type and
dfr:systemErr are now as early as possible initialized to prevent access
errors later.
Fix: #318

Bug-Fix: Fix undefined global var references

---

procedures/unit-testing-basics.ipf

Broken since 0c33b519 (Enable fixed log file names, 2022-10-30).

RunTest: Flip arguments

---

procedures/unit-testing-autorun.ipf

This allows to use code coverage determination to be used. Without it the UTF complains that AfterFileOpenHook is static and, without a module name, unaccessible.

unit-testing-autorun.ipf: Add missing ModuleName pragma

---

procedures/unit-testing-utils.ipf

We don't want to prefix it with 08 but instead we want to have 08 as precision which must stand *after* the percent sign.
While at it we also leverage the power of # and capital X to get a capital 0X prefix.
Bug introduced in b7bb12a4 (AreWavesEqual creates descriptive message in WAVE_DATA mode, 2021-03-04).

GetWavePointer_Impl: Fix return memory address

---

procedures/unit-testing-basics.ipf
procedures/unit-testing-constants.ipf
tests/Various.ipf

The old implementation does only increase the size of the wave one time
if the requested index is outside the capacity of the wave. This is okay
for smaller indexes but will return a too small wave if the requested
index is way larger than the current capacity of the wave.
This fixes the implementation in that way that it always calculates the
next suitable size that fits the requested index and resizes the wave
to always fit the requested index. This also includes a special logic to
use exponential growth with better asymptotical behavior for smaller
wave sizes and linear growth if the wave has a size that could have a
large impact on system memory.
With this EnsureLargeEnoughWaveSimple can no longer considered as
"simple" but the name is kept for compability. The documentation has
been …

Fix EnsureLargeEnoughWaveSimple for any index

---

procedures/unit-testing-utils.ipf
tests/Various.ipf

b3ca346 (GetWavePointer_Impl: Fix return memory address, 2022-12-20) has
fixed the output of the pointer names but also changed it to upper case
which made it less readable for the user.
Close #358

Use lowercase pointer names

---

procedures/unit-testing-assertion-wrappers.ipf

The function EQUAL_WAVE_WRAPPER() contains multiple calls to
EvaluateResults() which clear up the AssertionInfo state after its call.
This yield to this unexpected behavior if the first call cleared the
information and the second call need it for output.
To prevent this there are two options:
1. Call "return NaN" after the call to EvaluateResults()
2. Call EvaluateResults() with "cleanupInfo = 0" and call
UTF_Basics#CleanupInfoMsg() at the end.
Close #368

Fix: Show INFO() for CHECK_EQUAL_WAVE()

---

procedures/unit-testing-basics.ipf

Add INFO() output if a test case resulted in an abort or an RTE.
Close #367

Fix: INFO() for Aborts and RTEs

---

procedures/unit-testing-reporting.ipf

This make it easier to find the correct method in the history output.

Output full method name in assertion context

---

procedures/unit-testing-assertion-wrappers.ipf
procedures/unit-testing-autorun.ipf
procedures/unit-testing-basics.ipf
procedures/unit-testing-junit.ipf
procedures/unit-testing-reporting.ipf
procedures/unit-testing-tap.ipf
procedures/unit-testing-tracing-analytics.ipf
procedures/unit-testing-tracing-tracer.ipf
procedures/unit-testing-tracing.ipf
procedures/unit-testing-utils.ipf

Most calls to printf or fprintf are changed to UTF_Reporting#UTF_PrintStatusMessage. This function also ensures that the message is printed to stdout.
UTF_Reporting#UTF_PrintStatusMessage is now marked as threadsafe.
Close #329

Use UTF_PrintStatusMessage instead of printf

---

procedures/unit-testing-hooks.ipf

1. Execute AfterTestCaseUserHook independent from user hook
The execution of AfterTestCaseUserHook was dependent of the result of
the user hook. If the user hook failed for some reasons the
AfterTestCaseUserHook was never executed. This has been fixed that
AfterTestCaseUserHook is always executed independent of the user hook
result.
2. Remove unused ExecuteUserHook return value
After 38133d6 (Execute AfterTestCaseUserHook independent from user hook,
2023-01-24) the return value of ExecuteUserHook is no longer used in the
code. As such that it is removed completely from this function.
3. Skip test case end user hook if test case skipped
The user hooks for test case begin and end are now only then executed if
the test case itself is planed for execution.
Fix #384
Fix #385

Fix user hook issues #384 #385

---

procedures/unit-testing-basics.ipf

The function parameter are now checked if they are all optional as in the test cases. This fixes the loose function signature check in Igor 6 like it was done in 085e3d3 (Require optional parameter for test methods, 2022-10-07).
Close #270

Require optional function parameter for reentry

---

procedures/unit-testing-autorun.ipf
procedures/unit-testing-basics.ipf
procedures/unit-testing-junit.ipf
procedures/unit-testing-tap.ipf
procedures/unit-testing-tracing.ipf
procedures/unit-testing-utils-paths.ipf
procedures/unit-testing.ipf

At the start of RunTest the current home directory of the experiment file is fetched and cached in a global string. If for some reasons a test case changed to current home directory (for example storing the experiment file elsewhere) all UTF functions will still use the old home directory.
Close #287

Use cached home path for accessing files

---

docu/sphinx/source/guided-tour.rst

Broken since at least 0ceeff70 (gitlab-ci.yml: Adapt deployment job for new default branch, 2021-03-04).

docu/sphinx/source/guided-tour.rst: Adapt to main as default branch

---

docu/sphinx/source/advanced.rst

3bdcaaf (Introduce data generators as virtual test cases, 2023-01-26)
and 0a18141 (Treat user hooks as test cases for the results, 2023-01-13)
changed the behavior of pending RTE and aborts at the end of data
generator and user hooks. The documentation has been updated to reflect
this behavior.
Close #387

Doc: behavior of RTE/Abort in DG and UH

---

procedures/igortest-assertion-wrappers.ipf
procedures/igortest-assertions.ipf
tests/TestResultsTests/FailedTests.ipf

The string paramater for WARN_EQUAL_STR, CHECK_EQUAL_STR,
REQUIRE_EQUAL_STR, WARN_NEQ_STR, CHECK_NEQ_STR and REQUIRE_NEQ_STR are
now pass-by-value. This allows simpler usage and unify the api for the
*_EQUAL_* and *_NEQ_* variants.
These assertions were originally designed to be pass-by-reference to
catch the edge-case when the user provide a null string. There is no
longer a need take this in account as there are *_NULL_STR and
*_PROPER_STR assertions that are designed to check for these edge cases.
Close #363

*_EQUAL_STR and *_NEQ_STR are now pass-by-value

---

procedures/igortest-autorun.ipf
procedures/igortest-junit.ipf
procedures/igortest-reporting.ipf
procedures/igortest-tracing-analytics.ipf
procedures/igortest-tracing.ipf
procedures/igortest-utils-strings.ipf
procedures/igortest-utils.ipf

Strings from function arguments can be null and should be untrusted.
Using if(strlen(str)) to the check if its empty is therefore insecure
and prone to errors. These calls have been replaced with the better
UTF_Utils#IsEmpty.
Not all if(strlen(str)) are insecure and therefore only the mentioned
case is updated. If the string originate from a wave or an SVAR, which
cannot be null, the code if(strlen(str)) is kept and not replaced.
Close #303

Fix: Replace if(strlen(str)) with UTF_Utils#IsEmpty

---

docu/examples/example8-uncaught-runtime-errors.ipf
docu/sphinx/source/examples.rst
procedures/igortest-assertion-checks.ipf
procedures/igortest-assertion-wrappers.ipf
procedures/igortest-assertions.ipf
tests/VTTE.ipf

These assertions check the current RTE state and create an error if its
unexpected. This simplifies the user code to check for RTEs during
runtime.
Close #339

Add *_RTE, *_ANY_RTE and *_NO_RTE assertions

---

.gitlab-ci.yml

bcbfd75 (CI: Add Cobertura HTML report generator output, 2023-02-27)
added the wrong path for the deployment step.

Fix CI: Move to correct folder

---

Readme.md

This badge is an animated svg which shows the current line-coverage,
branch-coverage and method-coverage of the latest push to the main
branch.
The badges are created since bcbfd75 (CI: Add Cobertura HTML report
generator output, 2023-02-27).

Readme: Add coverage badge

---

procedures/igortest-basics.ipf

This prevents that an abortflag from a previous RunTest has some
influence for data generator of the current RunTest. Previously, the
abort flag is cleared at the test run begin hook which is called after
the data generator.
Close #431

Clear abort flag at the begin of RunTest

---

docu/sphinx/source/changelog.rst
procedures/igortest-basics.ipf
tests/VTTE.ipf

We use EqualWaves for comparison of dimension labels and that does it since forever case sensitive.
So we have to also output a difference if the labels only differ in case. Bug introduced in the initial version in 493779da (EQUAL_WAVE_WRAPPER: Work around EqualWaves dimension labels bug, 2019-03-12).

GenerateDimLabelDifference: Don't ignore case

---

procedures/igortest-tracing-analytics.ipf

Optimize the runtime of `GetTotals()` and `ShowTopFunctions`. The old function profiling result showed this:
```
Total time: 36.1456, Time in Function code: 36.1456 (100%)
Top function percentages:
Function igortest-tracing-analytics.ipf GetTotals: 100%
Annotated Top Functions:
*******************************************************************************************
Function: igortest-tracing-analytics.ipf igortest-tracing-analytics.ipf#GetTotals; Percent total 100%
*******************************************************************************************
[00]          	|static Function/WAVE GetTotals()
[00]          	|	variable i, numWaves
[00]          	|
[00]*         	|	TUFXOP_GetStorage/N="IUTF_TestRun" storage
[00]          	|	numWaves = DimSize(storage, UTF_ROW)
[00]          	| …
```

Tracing Analytics: Optimize GetTotals

---

procedures/igortest-autorun.ipf

The previous stored home path is unlikely the current home path of the experiment if the experiment is loaded into Igor. The autorun feature relyes on the correct home path to determine if an autorun should be executed or not.
This has been fixed in such a way that the AfterFileOpenHook will always clear the previous stored home path before checking the autorun configuration.
Close: #457

Autorun: Cleanup previous stored home path

---

docu/sphinx/source/advanced.rst
procedures/igortest-basics.ipf

- This allows a test case to revoke a registration of a background task to continue later with a reentry function.
- Added documentation
related to #466

Add utility function to unregister the IUTF background monitoring task

---

procedures/igortest-assertions.ipf
procedures/igortest-basics.ipf
procedures/igortest-hooks.ipf
procedures/igortest-reporting.ipf
tests/TestResultsTests/EasyTests.ipf

Both assertion abort the current testcase. Any registered reentry function is unregistered.
When SKIP_TESTCASE_EXPECT_FAILS is called, previously failed assertions in the same testcase are treated as expected failures.
close #467

Add SKIP_TESTCASE and SKIP_TESTCASE_EXPECT_FAILS assertions

---

docu/sphinx/source/code.rst
docu/sphinx/source/helpers.rst
procedures/igortest-assertion-wrappers.ipf
procedures/igortest-basics.ipf
procedures/igortest-debug.ipf
procedures/igortest-reporting.ipf

These changes increase the performance of the IUTF.
For 1000x CHECK_EQUAL_WAVES for the success case the rough numbers are:
Before: 7.37 s
After: 0.31 s
close #474 
close #472

Performance Increase

---

docu/sphinx/source/_static/custom.css
docu/sphinx/source/conf.py

We have updated our used sphinx and alabaster versions and they had some major breaking changes in the style and our current documentation looks a bit off. These changes ensures that we have the same style like before.

Fix sphinx documentation style

---

.gitlab-ci.yml

This prepares for the hosting migration from hosteurope to hetzner.

.gitlab-ci.yml: Prefer FTP_URL variable

---

procedures/igortest-basics.ipf
procedures/igortest-tracing-analytics.ipf
procedures/igortest-tracing-cobertura.ipf
procedures/igortest-tracing-tracer.ipf
procedures/igortest-tracing.ipf
tests/IMUnitTests/im-main.ipf
tests/IMUnitTests/main.ipf
tests/Tracing.ipf
tests/UnitTests/Tracing/CoberturaTests.ipf
tests/UnitTests/Tracing/ComplexityTests.ipf
tests/UnitTests/main.ipf
tests/test-tracing.ipf
tests/test-tracing2.ipf
tests/test-tracing_instrumented.ipf

With Igor 10 there is no code in specific regions of a switch statements allowed:
```igorpro
switch(condition)
print "no code supported here"
case VAR:
print "normal code"
break
print "no code supported here"
endswitch
```
Our tracing logic added Z_ function calls in such regions and therefore is a
logic added that prevents the addition of such. This fix does the following
changes to the coverage report:
- All comments, that are located in regions that do not support the execution of
Z_ functions (like certain regions in switch statements), are uncoverable.
- All compiler pragmas like #if and #else are now uncoverable.
Uncoverable lines are excluded from coverage report and will be rendered gray in
most visualizations.
This fix might change the overall code coverage slightly. This isn't …

Tracing: Fix switch statement tracing to support IP10
