- procedures/unit-testing-constants.ipf
INT16_WAVE is 0x10 and not 0x16.
Add also INT64_WAVE, DATAFOLDER_WAVE and WAVE_WAVE.
> Fix and extend the wave type constants

- procedures/unit-testing-junit.ipf
> Nificy properties output in JUNIT XML file

- procedures/unit-testing-basics.ipf
> Disallow combined output

- docu/sphinx/source/basic.rst
- procedures/unit-testing-comparators.ipf
> Document all three variants of the test assertions

- .gitlab-ci.yml
Reverts byte-physics/igor-unit-testing-framework#71
> Revert "Use Docker Image For Documentation"

- .gitlab-ci.yml
Unit tests are using the local Igor Pro 6 docker image.
> Add Unit Tests For Igor 6

- docu/examples/example13-multi-test-data.ipf
- docu/sphinx/source/advanced.rst
- docu/sphinx/source/basic.rst
- docu/sphinx/source/examples.rst
- internal_dev/example13-multi-test-data-with-fails.ipf
- internal_dev/example14-multi-test-data-with-background.ipf
- procedures/unit-testing-basics.ipf
- procedures/unit-testing-junit.ipf
Should solve https://github.com/byte-physics/igor-unit-testing-framework/issues/5
This enabled multi data test cases.
It also works in combination with test cases that monitor background activity.
> Support for test cases with multiple data input

- procedures/unit-testing-basics.ipf
Close https://github.com/byte-physics/igor-unit-testing-framework/issues/85
Previously only multi data test case function signatures were checked.
The problem in 85 was that the list contained a 'classic' test case that did not met the prototype function signature. With the multi data test cases, the code at the end of getTestCasesMatch requires now that the test cases returned by getTestCaseList have valid function signatures.
Before Multi Data TC support no TC function signatures were checked beforehand.
> The signature check for tc functions in getTestCaseList checks now checks all tc types

- internal_dev/fail-on-timeout-with-background-reentry.ipf
- procedures/unit-testing-basics.ipf
> Add fail on timeout

- .gitlab-ci.yml
- docu/sphinx/Makefile
And while at it we also remove the custom make targets for deployment.
This is not our standard approch now so it is quite confusing.
> Switch to docker runner over shell runner

- docu/examples/TAP_Examples/tap_example1a-uncaught-aborts.ipf
- docu/examples/TAP_Examples/tap_example1b-warn_and_error.ipf
> Bugfix tap examples

- procedures/unit-testing-utils.ipf
> Fix tag finding

- docu/sphinx/source/advanced.rst
- docu/sphinx/source/junit.xml
- docu/sphinx/source/junit.xsd
- Added example XML and XSD definition sheet for the JUNIT implementation that
the IUTF uses.
- Added links to official external sources of at the Jenkins xunit
implementation on github.
close https://github.com/byte-physics/igor-unit-testing-framework/issues/134
> Added JUNIT reference and updated JUNIT section in advanced.rst file

- .gitlab-ci.yml
- procedures/unit-testing-assertion-checks.ipf
- tests/VTTE.ipf
The docker image is broken currently.
> .gitlab-ci.yml: Remove IP9 testing for now

- procedures/unit-testing-basics.ipf
- procedures/unit-testing-junit.ipf
Previously only the last failure message appeared in the JUnit output.
Now for each failed assertion a <failure> or <error> tag is written,
depending if the test case aborted or not.
Also <system-err> output was extended accordingly to include all
fail messages.
The xml file with multiple failure tags was checked against the
reference xsd schema file and it validates (using xmllint)
close https://github.com/byte-physics/igor-unit-testing-framework/issues/26
> With JUnit enabled a <failure> tag for each failed assertion is written

- .gitlab-ci.yml
- procedures/unit-testing-assertion-wrappers.ipf
- procedures/unit-testing-assertions.ipf
> Fix documentation bugs

- procedures/unit-testing-assertion-checks.ipf
- procedures/unit-testing-assertion-wrappers.ipf
- procedures/unit-testing-assertions.ipf
- tests/VTTE.ipf
> Add assertions for <=, <, >, >=

- procedures/unit-testing-utils.ipf
- tests/Various.ipf
This is a generic function to return the memory address of a wave which
works on all Igor Pro versions.
> Add GetWavePointer

- procedures/unit-testing-tracing.ipf
Adds line numbers in front of the output in the html files from tracing.
> Add line numbers in front of tracing result html output

- docu/sphinx/source/advanced.rst
- procedures/unit-testing-tracing.ipf
- tests/test-tracing.ipf
- tests/test-tracing_instrumented.ipf
Changes to support also Macros in instrumentation.
close https://github.com/byte-physics/igor-unit-testing-framework/issues/234
> Support macros in instrumentation

- docu/examples/example2-plain.ipf
- internal_dev/IM_Test3.ipf
- procedures/unit-testing-assertion-wrappers.ipf
- tests/VTTE.ipf
> Make string comparisons always case sensitive by default

- internal_dev/TracingZError.ipf
> TracingZError: Remove BOM

- docu/sphinx/source/advanced.rst
- procedures/unit-testing-tracing-analytics.ipf
- procedures/unit-testing-tracing.ipf
- procedures/unit-testing-utils.ipf
- procedures/unit-testing.ipf
> Gather Top Functions

- procedures/unit-testing-utils.ipf
- tests/Various.ipf
> DiffString: Enable null string parameter

- create-public-release.sh
- docu/docker/debian/Dockerfile
- docu/docker/doxygen/Dockerfile
- docu/docker/sphinx/Dockerfile
- docu/docker/sphinx/Makefile
- docu/scripts/docu-sphinx.sh
- docu/sphinx/source/changelog.rst
- docu/sphinx/source/index.rst
And get the documentation docker containers work again.
Required as first step for #346.
> Add historic changelog

- procedures/unit-testing-tap.ipf
This makes it easier to understand the TAP output.
> Prefix TAP description with the test case name

- Readme.md
This is the rewrite of the Readme.
> Rewrite of Readme.md

- procedures/unit-testing-basics.ipf
RunTest could call the test suite end hook without calling the begin hook first. This can happen if the user aborts the TEST_BEGIN_OVERRIDE user hook.
This is now fixed as such as it is checked if in the current RunTest run it can guaranteed that IUTF_TEST_SUITE_BEGIN_CONST was ever called before calling IUTF_TEST_SUITE_END_CONST.
Close #347
> Fix: Execute test suite end hook only if started

- docu/sphinx/source/basic.rst
- procedures/igortest-basics.ipf
> Document user abort key shortcuts

- procedures/igortest-junit.ipf
> Include custom INFO() in JUnit

- procedures/igortest-reporting.ipf
- tests/TestResultsTests/EasyTests.ipf
> Include custom INFO() in STDERR

- Readme.md
- docu/sphinx/source/changelog.rst
Up to date: 5085682d (Merge pull request #426 from byte-physics/mb/feature/6-compilation-test, 2023-03-15)
> changelog.rst: Update it

- .pre-commit-config.yaml
And ignore the xop folder as that is third-party content.
> .pre-commit-config.yaml: Add end-of-file-fixer

- .gitlab-ci.yml
- docu/sphinx/source/conf.py
> .gitlab-ci.yml: Switch to new runner on sonoma
